name: Bump unversioned casks

on:
  push:
    branches:
      - debug-bump-unversioned-casks
  # schedule:
  #   - cron: '0 * * * *'

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  bump-unversioned-casks:
    if: startsWith(github.repository, 'Homebrew/')
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: BrewTestBot

      - name: Checkout command PR
        run: |
          pushd "$(brew --repo)"
          gh pr checkout https://github.com/Homebrew/brew/pull/9423
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Workaround until the `cache` action uses the changes from
      # https://github.com/actions/toolkit/pull/580.
      - name: Unlink workspace
        run: |
          mv "${GITHUB_WORKSPACE}" "${GITHUB_WORKSPACE}-link"
          mkdir "${GITHUB_WORKSPACE}"

      - name: Cache Homebrew Gems
        uses: actions/cache@v2
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Gems
        run: brew install-bundler-gems

      - name: Generate cache ID
        id: cache-id
        run: |
          echo "::set-output name=time::$(date +%s)"

      - name: Cache state
        uses: actions/cache@v2
        with:
          path: ~/bump-unversioned-casks-state.json
          key: bump-unversioned-casks-${{ steps.cache-id.outputs.time }}
          restore-keys: bump-unversioned-casks-

      # Workaround until the `cache` action uses the changes from
      # https://github.com/actions/toolkit/pull/580.
      - name: Re-link workspace
        run: |
          rmdir "${GITHUB_WORKSPACE}"
          mv "${GITHUB_WORKSPACE}-link" "${GITHUB_WORKSPACE}"

      - name: Run brew bump-unversioned-casks ${{ github.repository }}
        run: |
          brew bump-unversioned-casks --state-file ~/bump-unversioned-casks-state.json --limit 10 '${{ github.repository }}'
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        timeout-minutes: 30
        continue-on-error: true

      # Workaround until the `cache` action uses the changes from
      # https://github.com/actions/toolkit/pull/580.
      - name: Unlink workspace
        run: |
          rm "${GITHUB_WORKSPACE}"
          mkdir "${GITHUB_WORKSPACE}"
